import { Providers } from "../providers/providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <script
          src="//code.tidio.co/ctthkrbemuzwkzdtga5zcn6hwozf1vfs.js"
          async
        ></script>
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
